## Install `simple_salesforce`  module

Remove the comment symbol (#) to run `!pip install simple_salesforce`. Once this module is installed, you can comment it out again.

In [56]:
#!pip install simple_salesforce

## Import dependencies

In [57]:
import json
from sqlalchemy import create_engine
from datetime import date
import pandas as pd
import pymysql
import numpy as np
pymysql.install_as_MySQLdb()

## Import configuration variables

In [58]:
# import sys
# sys.path.append('../../../../')
from config import sf_username, sf_password, sf_security_token
from config import remote_db_endpoint, remote_db_port
from config import remote_db_name, remote_db_user, remote_db_pwd

## Set up `simple_salesforce`

Pass in the username, password, and security token here. The security token contains information about your org.

In [59]:
from simple_salesforce import Salesforce
sf = Salesforce(username=sf_username, password=sf_password, security_token=sf_security_token)

## Connect to your MySQL database

In [60]:
engine = create_engine(f"mysql://{remote_db_user}:{remote_db_pwd}@{remote_db_endpoint}:{remote_db_port}/{remote_db_name}")
conn = engine.connect()

## Query Data

In [61]:
class_participant_data = pd.read_sql("SELECT * FROM classparticipant", conn)
class_participant_data.head(10)

   ID_ClassParticipant  ID_Student  ID_Class   StartDate EndDate
0                    1          33         1  2020-03-16    None
1                    2          34         1  2020-03-16    None
2                    3          35         1  2020-03-16    None
3                    4          62         1  2020-03-16    None
4                    5          36         1  2020-03-16    None
5                    6          37         1  2020-03-16    None
6                    7          38         1  2020-03-16    None
7                    8          39         1  2020-03-16    None
8                    9          40         1  2020-03-16    None
9                   10          41         1  2020-03-16    None

## CREATE Course LookUp table #1 from Class Table

In [62]:
query=sf.query_all_iter("SELECT ID_Class__c, Name FROM Class__c")

In [63]:
query

In [64]:
class_lookup_list = []

for rec in query:
    
    sf_record = {
        'Class_lookup_ID':rec['Name'],
        'ID_Class': rec['ID_Class__c']
              
    }
    class_lookup_list.append(sf_record)

In [65]:
class_lookup_list

[{'Class_lookup_ID': 'a0B3h000001jxIK', 'ID_Class': '1'},
 {'Class_lookup_ID': 'a0B3h000001jxIP', 'ID_Class': '2'},
 {'Class_lookup_ID': 'a0B3h000001jxIZ', 'ID_Class': '4'},
 {'Class_lookup_ID': 'a0B3h000001jxIU', 'ID_Class': '3'}]

In [66]:
class_lookup_df = pd.DataFrame(class_lookup_list)

class_lookup_df.head(20)

   Class_lookup_ID ID_Class
0  a0B3h000001jxIK        1
1  a0B3h000001jxIP        2
2  a0B3h000001jxIZ        4
3  a0B3h000001jxIU        3

In [67]:
class_lookup_df.dtypes

Class_lookup_ID    object
ID_Class           object
dtype: object

In [68]:
class_lookup_df["Class_lookup_ID"]=class_lookup_df["Class_lookup_ID"].astype(str)
class_lookup_df["ID_Class"]=class_lookup_df["ID_Class"].astype(str)

In [69]:
class_lookup_df.dtypes

Class_lookup_ID    object
ID_Class           object
dtype: object

## CREATE Course LookUp table #2 from Student Table

In [70]:
query=sf.query_all_iter("SELECT ID_Student__c, Name FROM Student__c")

In [71]:
query

In [72]:
student_lookup_list = []

for rec in query:
    
    sf_record = {
        'Student_lookup_ID':rec['Name'],
        'ID_Student': rec['ID_Student__c']
              
    }
    student_lookup_list.append(sf_record)

In [73]:
student_lookup_list

[{'Student_lookup_ID': 'a0A3h000003L6S6', 'ID_Student': 47.0},
 {'Student_lookup_ID': 'a0A3h000003L6SL', 'ID_Student': 50.0},
 {'Student_lookup_ID': 'a0A3h000003L6Qy', 'ID_Student': 33.0},
 {'Student_lookup_ID': 'a0A3h000003L6Sf', 'ID_Student': 54.0},
 {'Student_lookup_ID': 'a0A3h000003L6Sk', 'ID_Student': 55.0},
 {'Student_lookup_ID': 'a0A3h000003L6Su', 'ID_Student': 57.0},
 {'Student_lookup_ID': 'a0A3h000003L6SQ', 'ID_Student': 51.0},
 {'Student_lookup_ID': 'a0A3h000003L6Sa', 'ID_Student': 53.0},
 {'Student_lookup_ID': 'a0A3h000003L6RN', 'ID_Student': 38.0},
 {'Student_lookup_ID': 'a0A3h000003L6SV', 'ID_Student': 52.0},
 {'Student_lookup_ID': 'a0A3h000003L6T9', 'ID_Student': 60.0},
 {'Student_lookup_ID': 'a0A3h000003L6RI', 'ID_Student': 37.0},
 {'Student_lookup_ID': 'a0A3h000003L6R3', 'ID_Student': 34.0},
 {'Student_lookup_ID': 'a0A3h000003L6R8', 'ID_Student': 35.0},
 {'Student_lookup_ID': 'a0A3h000003L6SG', 'ID_Student': 49.0},
 {'Student_lookup_ID': 'a0A3h000003L6TE', 'ID_Student': 61.0},
 {'Student_lookup_ID': 'a0A3h000003L6Rm', 'ID_Student': 43.0},
 {'Student_lookup_ID': 'a0A3h000003L6TJ', 'ID_Student': 62.0},
 {'Student_lookup_ID': 'a0A3h000003L6RS', 'ID_Student': 39.0},
 {'Student_lookup_ID': 'a0A3h000003L6Rc', 'ID_Student': 41.0},
 {'Student_lookup_ID': 'a0A3h000003L6Rr', 'ID_Student': 44.0},
 {'Student_lookup_ID': 'a0A3h000003L6S1', 'ID_Student': 46.0},
 {'Student_lookup_ID': 'a0A3h000003L6T4', 'ID_Student': 59.0},
 {'Student_lookup_ID': 'a0A3h000003L6RD', 'ID_Student': 36.0},
 {'Student_lookup_ID': 'a0A3h000003L6SB', 'ID_Student': 48.0},
 {'Student_lookup_ID': 'a0A3h000003L6Sp', 'ID_Student': 56.0},
 {'Student_lookup_ID': 'a0A3h000003L6Rw', 'ID_Student': 45.0},
 {'Student_lookup_ID': 'a0A3h000003L6RX', 'ID_Student': 40.0},
 {'Student_lookup_ID': 'a0A3h000003L6Sz', 'ID_Student': 58.0},
 {'Student_lookup_ID': 'a0A3h000003L6Rh', 'ID_Student': 42.0}]

In [74]:
student_lookup_df = pd.DataFrame(student_lookup_list)

student_lookup_df.head(5)

  Student_lookup_ID  ID_Student
0   a0A3h000003L6S6        47.0
1   a0A3h000003L6SL        50.0
2   a0A3h000003L6Qy        33.0
3   a0A3h000003L6Sf        54.0
4   a0A3h000003L6Sk        55.0

In [75]:
student_lookup_df.dtypes

Student_lookup_ID     object
ID_Student           float64
dtype: object

In [76]:
#student_lookup_df["ID_Student"]=student_lookup_df["ID_Student"].astype(str)

In [77]:
new = np.array(student_lookup_df["ID_Student"])

In [78]:
student_lookup_df["ID_Student"]=new.astype(int)

In [79]:
student_lookup_df["ID_Student"]

0     47
1     50
2     33
3     54
4     55
5     57
6     51
7     53
8     38
9     52
10    60
11    37
12    34
13    35
14    49
15    61
16    43
17    62
18    39
19    41
20    44
21    46
22    59
23    36
24    48
25    56
26    45
27    40
28    58
29    42
Name: ID_Student, dtype: int32

In [80]:
student_lookup_df["ID_Student"]=student_lookup_df["ID_Student"].astype(str)

In [81]:
student_lookup_df.head()

  Student_lookup_ID ID_Student
0   a0A3h000003L6S6         47
1   a0A3h000003L6SL         50
2   a0A3h000003L6Qy         33
3   a0A3h000003L6Sf         54
4   a0A3h000003L6Sk         55

In [82]:
student_lookup_df.dtypes

Student_lookup_ID    object
ID_Student           object
dtype: object

## Joining the tables

In [83]:
query='''
    SELECT 
        cp.*
    FROM
        classparticipant cp
        INNER JOIN class c
        ON c.ID_Class=cp.ID_Class
        INNER JOIN student s
        ON cp.ID_Student=s.ID_Student
'''

class_participant_data_df=pd.read_sql(query, conn)
class_participant_data_df.head()

   ID_ClassParticipant  ID_Student  ID_Class   StartDate EndDate
0                    1          33         1  2020-03-16    None
1                    2          34         1  2020-03-16    None
2                    3          35         1  2020-03-16    None
3                    4          62         1  2020-03-16    None
4                    5          36         1  2020-03-16    None

In [84]:
class_participant_data_df.rename(columns={
    'ID_ClassParticipant':'ID_ClassParticipant__c',
    'StartDate':'StartDate__c',
    'EndDate':'EndDate__c',
}, inplace=True)

class_participant_data_df.head(5)

   ID_ClassParticipant__c  ID_Student  ID_Class StartDate__c EndDate__c
0                       1          33         1   2020-03-16       None
1                       2          34         1   2020-03-16       None
2                       3          35         1   2020-03-16       None
3                       4          62         1   2020-03-16       None
4                       5          36         1   2020-03-16       None

In [85]:
class_participant_data_df.dtypes

ID_ClassParticipant__c     int64
ID_Student                 int64
ID_Class                   int64
StartDate__c              object
EndDate__c                object
dtype: object

In [86]:
class_participant_data_df.astype({'ID_ClassParticipant__c': 'str'}).dtypes

ID_ClassParticipant__c    object
ID_Student                 int64
ID_Class                   int64
StartDate__c              object
EndDate__c                object
dtype: object

In [87]:
class_participant_data_df["ID_ClassParticipant__c"]=class_participant_data_df["ID_ClassParticipant__c"].astype(str)
class_participant_data_df["ID_Student"]=class_participant_data_df["ID_Student"].astype(str)
class_participant_data_df["ID_Class"]=class_participant_data_df["ID_Class"].astype(str)

In [88]:
class_participant_data_df.dtypes

ID_ClassParticipant__c    object
ID_Student                object
ID_Class                  object
StartDate__c              object
EndDate__c                object
dtype: object

In [89]:
class_participant_data_df1 = pd.merge(class_participant_data_df, class_lookup_df,how='left')
class_participant_data_df1.head(5)

,ID_ClassParticipant__c,ID_Student,ID_Class,StartDate__c,EndDate__c,Class_lookup_ID
0,1,33,1,2020-03-16,None,a0B3h000001jxIK
1,2,34,1,2020-03-16,None,a0B3h000001jxIK
2,3,35,1,2020-03-16,None,a0B3h000001jxIK
3,4,62,1,2020-03-16,None,a0B3h000001jxIK
4,5,36,1,2020-03-16,None,a0B3h000001jxIK

In [90]:
class_participant_data_df2 = pd.merge(class_participant_data_df1,student_lookup_df,how='left', on="ID_Student")
class_participant_data_df2.head()
class_participant_data_df2.fillna(0)

,ID_ClassParticipant__c,ID_Student,ID_Class,StartDate__c,EndDate__c,Class_lookup_ID,Student_lookup_ID
0,1,33,1,2020-03-16,0,a0B3h000001jxIK,a0A3h000003L6Qy
1,2,34,1,2020-03-16,0,a0B3h000001jxIK,a0A3h000003L6R3
2,3,35,1,2020-03-16,0,a0B3h000001jxIK,a0A3h000003L6R8
3,4,62,1,2020-03-16,0,a0B3h000001jxIK,a0A3h000003L6TJ
4,5,36,1,2020-03-16,0,a0B3h000001jxIK,a0A3h000003L6RD
5,6,37,1,2020-03-16,0,a0B3h000001jxIK,a0A3h000003L6RI
6,7,38,1,2020-03-16,0,a0B3h000001jxIK,a0A3h000003L6RN
7,8,39,1,2020-03-16,0,a0B3h000001jxIK,a0A3h000003L6RS
8,9,40,1,2020-03-16,0,a0B3h000001jxIK,a0A3h000003L6RX
9,10,41,1,2020-03-16,0,a0B3h000001jxIK,a0A3h000003L6Rc
10,11,42,1,2020-03-16,0,a0B3h000001jxIK,a0A3h000003L6Rh
11,12,43,1,2020-03-16,0,a0B3h000001jxIK,a0A3h000003L6Rm
12,13,46,1,2020-03-16,0,a0B3h000001jxIK,a0A3h000003L6S1
13,14,47,1,2020-03-16,0,a0B3h000001jxIK,a0A3h000003L6S6
14,15,48,1,2020-03-16,0,a0B3h000001jxIK,a0A3h000003L6SB
15,16,49,1,2020-03-16,0,a0B3h000001jxIK,a0A3h000003L6SG
16,17,50,1,2020-03-16,0,a0B3h000001jxIK,a0A3h000003L6SL
17,18,51,1,2020-03-16,0,a0B3h000001jxIK,a0A3h000003L6SQ
18,20,53,1,2020-03-16,0,a0B3h000001jxIK,a0A3h000003L6Sa
19,21,54,1,2020-03-16,0,a0B3h000001jxIK,a0A3h000003L6Sf
20,22,55,1,2020-03-16,0,a0B3h000001jxIK,a0A3h000003L6Sk
21,23,56,1,2020-03-16,0,a0B3h000001jxIK,a0A3h000003L6Sp
22,24,57,1,2020-03-16,0,a0B3h000001jxIK,a0A3h000003L6Su
23,25,58,1,2020-03-16,0,a0B3h000001jxIK,a0A3h000003L6Sz
24,26,59,1,2020-03-16,0,a0B3h000001jxIK,a0A3h000003L6T4
25,27,60,1,2020-03-16,0,a0B3h000001jxIK,a0A3h000003L6T9
26,28,61,1,2020-03-16,0,a0B3h000001jxIK,a0A3h000003L6TE
27,29,44,1,2020-03-16,0,a0B3h000001jxIK,a0A3h000003L6Rr

In [91]:
class_participant_data_df2['StartDate__c'] = pd.to_datetime(class_participant_data_df2['StartDate__c']).dt.date
class_participant_data_df2['EndDate__c'] = pd.to_datetime(class_participant_data_df2['EndDate__c']).dt.date
#class_participant_data_df2.drop(columns = ['EndDate__c'], inplace=True)
class_participant_data_df2.head()

,ID_ClassParticipant__c,ID_Student,ID_Class,StartDate__c,EndDate__c,Class_lookup_ID,Student_lookup_ID
0,1,33,1,2020-03-16,NaT,a0B3h000001jxIK,a0A3h000003L6Qy
1,2,34,1,2020-03-16,NaT,a0B3h000001jxIK,a0A3h000003L6R3
2,3,35,1,2020-03-16,NaT,a0B3h000001jxIK,a0A3h000003L6R8
3,4,62,1,2020-03-16,NaT,a0B3h000001jxIK,a0A3h000003L6TJ
4,5,36,1,2020-03-16,NaT,a0B3h000001jxIK,a0A3h000003L6RD

In [92]:
class_participant_data_records = class_participant_data_df2.to_dict(orient='records')
class_participant_data_records

[{'ID_ClassParticipant__c': '1',
  'ID_Student': '33',
  'ID_Class': '1',
  'StartDate__c': datetime.date(2020, 3, 16),
  'EndDate__c': NaT,
  'Class_lookup_ID': 'a0B3h000001jxIK',
  'Student_lookup_ID': 'a0A3h000003L6Qy'},
 {'ID_ClassParticipant__c': '2',
  'ID_Student': '34',
  'ID_Class': '1',
  'StartDate__c': datetime.date(2020, 3, 16),
  'EndDate__c': NaT,
  'Class_lookup_ID': 'a0B3h000001jxIK',
  'Student_lookup_ID': 'a0A3h000003L6R3'},
 {'ID_ClassParticipant__c': '3',
  'ID_Student': '35',
  'ID_Class': '1',
  'StartDate__c': datetime.date(2020, 3, 16),
  'EndDate__c': NaT,
  'Class_lookup_ID': 'a0B3h000001jxIK',
  'Student_lookup_ID': 'a0A3h000003L6R8'},
 {'ID_ClassParticipant__c': '4',
  'ID_Student': '62',
  'ID_Class': '1',
  'StartDate__c': datetime.date(2020, 3, 16),
  'EndDate__c': NaT,
  'Class_lookup_ID': 'a0B3h000001jxIK',
  'Student_lookup_ID': 'a0A3h000003L6TJ'},
 {'ID_ClassParticipant__c': '5',
  'ID_Student': '36',
  'ID_Class': '1',
  'StartDate__c': datetime.date(2020, 3, 16),
  'EndDate__c': NaT,
  'Class_lookup_ID': 'a0B3h000001jxIK',
  'Student_lookup_ID': 'a0A3h000003L6RD'},
 {'ID_ClassParticipant__c': '6',
  'ID_Student': '37',
  'ID_Class': '1',
  'StartDate__c': datetime.date(2020, 3, 16),
  'EndDate__c': NaT,
  'Class_lookup_ID': 'a0B3h000001jxIK',
  'Student_lookup_ID': 'a0A3h000003L6RI'},
 {'ID_ClassParticipant__c': '7',
  'ID_Student': '38',
  'ID_Class': '1',
  'StartDate__c': datetime.date(2020, 3, 16),
  'EndDate__c': NaT,
  'Class_lookup_ID': 'a0B3h000001jxIK',
  'Student_lookup_ID': 'a0A3h000003L6RN'},
 {'ID_ClassParticipant__c': '8',
  'ID_Student': '39',
  'ID_Class': '1',
  'StartDate__c': datetime.date(2020, 3, 16),
  'EndDate__c': NaT,
  'Class_lookup_ID': 'a0B3h000001jxIK',
  'Student_lookup_ID': 'a0A3h000003L6RS'},
 {'ID_ClassParticipant__c': '9',
  'ID_Student': '40',
  'ID_Class': '1',
  'StartDate__c': datetime.date(2020, 3, 16),
  'EndDate__c': NaT,
  'Class_lookup_ID': 'a0B3h000001jxIK',
  'Student_lookup_ID': 'a0A3h000003L6RX'},
 {'ID_ClassParticipant__c': '10',
  'ID_Student': '41',
  'ID_Class': '1',
  'StartDate__c': datetime.date(2020, 3, 16),
  'EndDate__c': NaT,
  'Class_lookup_ID': 'a0B3h000001jxIK',
  'Student_lookup_ID': 'a0A3h000003L6Rc'},
 {'ID_ClassParticipant__c': '11',
  'ID_Student': '42',
  'ID_Class': '1',
  'StartDate__c': datetime.date(2020, 3, 16),
  'EndDate__c': NaT,
  'Class_lookup_ID': 'a0B3h000001jxIK',
  'Student_lookup_ID': 'a0A3h000003L6Rh'},
 {'ID_ClassParticipant__c': '12',
  'ID_Student': '43',
  'ID_Class': '1',
  'StartDate__c': datetime.date(2020, 3, 16),
  'EndDate__c': NaT,
  'Class_lookup_ID': 'a0B3h000001jxIK',
  'Student_lookup_ID': 'a0A3h000003L6Rm'},
 {'ID_ClassParticipant__c': '13',
  'ID_Student': '46',
  'ID_Class': '1',
  'StartDate__c': datetime.date(2020, 3, 16),
  'EndDate__c': NaT,
  'Class_lookup_ID': 'a0B3h000001jxIK',
  'Student_lookup_ID': 'a0A3h000003L6S1'},
 {'ID_ClassParticipant__c': '14',
  'ID_Student': '47',
  'ID_Class': '1',
  'StartDate__c': datetime.date(2020, 3, 16),
  'EndDate__c': NaT,
  'Class_lookup_ID': 'a0B3h000001jxIK',
  'Student_lookup_ID': 'a0A3h000003L6S6'},
 {'ID_ClassParticipant__c': '15',
  'ID_Student': '48',
  'ID_Class': '1',
  'StartDate__c': datetime.date(2020, 3, 16),
  'EndDate__c': NaT,
  'Class_lookup_ID': 'a0B3h000001jxIK',
  'Student_lookup_ID': 'a0A3h000003L6SB'},
 {'ID_ClassParticipant__c': '16',
  'ID_Student': '49',
  'ID_Class': '1',
  'StartDate__c': datetime.date(2020, 3, 16),
  'EndDate__c': NaT,
  'Class_lookup_ID': 'a0B3h000001jxIK',
  'Student_lookup_ID': 'a0A3h000003L6SG'},
 {'ID_ClassParticipant__c': '17',
  'ID_Student': '50',
  'ID_Class': '1',
  'StartDate__c': datetime.date(2020, 3, 16),
  'EndDate__c': NaT,
  'Class_lookup_ID': 'a0B3h000001jxIK',
  'Student_lookup_ID': 'a0A3h000003L6SL'},
 {'ID_ClassParticipant__c': '18',
  'ID_Student': '51',
  'ID_Class': '1',
  'StartDate__c': datetime.date(2020, 3, 16),
  'EndDate__c': NaT,
  'Class_lookup_ID': 'a0B3h000001jxIK',
  'Student_lookup_ID': 'a0A3h000003L6SQ'},
 {'ID_ClassParticipant__c': '20',
  'ID_Student': '53',
  'ID_Class': '1',
  'StartDate__c': datetime.date(2020, 3, 16),
  'EndDate__c': NaT,
  'Class_lookup_ID': 'a0B3h000001jxIK',
  'Student_lookup_ID': 'a0A3h000003L6Sa'},
 {'ID_ClassParticipant__c': '21',
  'ID_Student': '54',
  'ID_Class': '1',
  'StartDate__c': datetime.date(2020, 3, 16),
  'EndDate__c': NaT,
  'Class_lookup_ID': 'a0B3h000001jxIK',
  'Student_lookup_ID': 'a0A3h000003L6Sf'},
 {'ID_ClassParticipant__c': '22',
  'ID_Student': '55',
  'ID_Class': '1',
  'StartDate__c': datetime.date(2020, 3, 16),
  'EndDate__c': NaT,
  'Class_lookup_ID': 'a0B3h000001jxIK',
  'Student_lookup_ID': 'a0A3h000003L6Sk'},
 {'ID_ClassParticipant__c': '23',
  'ID_Student': '56',
  'ID_Class': '1',
  'StartDate__c': datetime.date(2020, 3, 16),
  'EndDate__c': NaT,
  'Class_lookup_ID': 'a0B3h000001jxIK',
  'Student_lookup_ID': 'a0A3h000003L6Sp'},
 {'ID_ClassParticipant__c': '24',
  'ID_Student': '57',
  'ID_Class': '1',
  'StartDate__c': datetime.date(2020, 3, 16),
  'EndDate__c': NaT,
  'Class_lookup_ID': 'a0B3h000001jxIK',
  'Student_lookup_ID': 'a0A3h000003L6Su'},
 {'ID_ClassParticipant__c': '25',
  'ID_Student': '58',
  'ID_Class': '1',
  'StartDate__c': datetime.date(2020, 3, 16),
  'EndDate__c': NaT,
  'Class_lookup_ID': 'a0B3h000001jxIK',
  'Student_lookup_ID': 'a0A3h000003L6Sz'},
 {'ID_ClassParticipant__c': '26',
  'ID_Student': '59',
  'ID_Class': '1',
  'StartDate__c': datetime.date(2020, 3, 16),
  'EndDate__c': NaT,
  'Class_lookup_ID': 'a0B3h000001jxIK',
  'Student_lookup_ID': 'a0A3h000003L6T4'},
 {'ID_ClassParticipant__c': '27',
  'ID_Student': '60',
  'ID_Class': '1',
  'StartDate__c': datetime.date(2020, 3, 16),
  'EndDate__c': NaT,
  'Class_lookup_ID': 'a0B3h000001jxIK',
  'Student_lookup_ID': 'a0A3h000003L6T9'},
 {'ID_ClassParticipant__c': '28',
  'ID_Student': '61',
  'ID_Class': '1',
  'StartDate__c': datetime.date(2020, 3, 16),
  'EndDate__c': NaT,
  'Class_lookup_ID': 'a0B3h000001jxIK',
  'Student_lookup_ID': 'a0A3h000003L6TE'},
 {'ID_ClassParticipant__c': '29',
  'ID_Student': '44',
  'ID_Class': '1',
  'StartDate__c': datetime.date(2020, 3, 16),
  'EndDate__c': NaT,
  'Class_lookup_ID': 'a0B3h000001jxIK',
  'Student_lookup_ID': 'a0A3h000003L6Rr'}]

In [93]:
class_participant_data_df2.dtypes

ID_ClassParticipant__c            object
ID_Student                        object
ID_Class                          object
StartDate__c                      object
EndDate__c                datetime64[ns]
Class_lookup_ID                   object
Student_lookup_ID                 object
dtype: object

In [94]:
for rec in class_participant_data_records:
 
    record = {
        'ID_ClassParticipant__c':rec['ID_ClassParticipant__c'],
        'ID_Student__c':rec['ID_Student'],
        'ID_Class__c': rec['ID_Class'],
        'StartDate__c': str(rec['StartDate__c']),
        'Class__c': rec['Class_lookup_ID'],
        'Student__c':rec['Student_lookup_ID'],
    }
    
    try:
        sf.Class_participant__c.create(record)
    except Exception as e:
        print(e)

In [95]:
## Deleting the Records

In [52]:
#course_records = sf.query("SELECT Name FROM Class_participant__c")
#course_records

OrderedDict([('totalSize', 168),
             ('done', True),
             ('records',
              [OrderedDict([('attributes',
                             OrderedDict([('type', 'Class_participant__c'),
                                          ('url',
                                           '/services/data/v42.0/sobjects/Class_participant__c/a0C3h0000019riREAQ')])),
                            ('Name', 'a0C3h0000019riR')]),
               OrderedDict([('attributes',
                             OrderedDict([('type', 'Class_participant__c'),
                                          ('url',
                                           '/services/data/v42.0/sobjects/Class_participant__c/a0C3h0000019rilEAA')])),
                            ('Name', 'a0C3h0000019ril')]),
               OrderedDict([('attributes',
                             OrderedDict([('type', 'Class_participant__c'),
                                          ('url',
                                           '/services/data/v42.0/sobjects/Class_participant__c/a0C3h0000019rjKEAQ')])),
                            ('Name', 'a0C3h0000019rjK')]),
               OrderedDict([('attributes',
                             OrderedDict([('type', 'Class_participant__c'),
                                          ('url',
                                           '/services/data/v42.0/sobjects/Class_participant__c/a0C3h0000019rkSEAQ')])),
                            ('Name', 'a0C3h0000019rkS')]),
               OrderedDict([('attributes',
                             OrderedDict([('type', 'Class_participant__c'),
                                          ('url',
                                           '/services/data/v42.0/sobjects/Class_participant__c/a0C3h0000019riWEAQ')])),
                            ('Name', 'a0C3h0000019riW')]),
               OrderedDict([('attributes',
                             OrderedDict([('type', 'Class_participant__c'),
                                          ('url',
                                           '/services/data/v42.0/sobjects/Class_participant__c/a0C3h0000019rgkEAA')])),
                            ('Name', 'a0C3h0000019rgk')]),
               OrderedDict([('attributes',
                             OrderedDict([('type', 'Class_participant__c'),
                                          ('url',
                                           '/services/data/v42.0/sobjects/Class_participant__c/a0C3h0000019rjPEAQ')])),
                            ('Name', 'a0C3h0000019rjP')]),
               OrderedDict([('attributes',
                             OrderedDict([('type', 'Class_participant__c'),
                                          ('url',
                                           '/services/data/v42.0/sobjects/Class_participant__c/a0C3h0000019sZaEAI')])),
                            ('Name', 'a0C3h0000019sZa')]),
               OrderedDict([('attributes',
                             OrderedDict([('type', 'Class_participant__c'),
                                          ('url',
                                           '/services/data/v42.0/sobjects/Class_participant__c/a0C3h0000019sZbEAI')])),
                            ('Name', 'a0C3h0000019sZb')]),
               OrderedDict([('attributes',
                             OrderedDict([('type', 'Class_participant__c'),
                                          ('url',
                                           '/services/data/v42.0/sobjects/Class_participant__c/a0C3h0000019rhsEAA')])),
                            ('Name', 'a0C3h0000019rhs')]),
               OrderedDict([('attributes',
                             OrderedDict([('type', 'Class_participant__c'),
                                          ('url',
                                           '/services/data/v42.0/sobjects/Class_participant__c/a0C3h0000019rgzEAA')])),
                            ('Name', 'a0C3h0000019rgz')]),
               OrderedDict([('attributes',
                             OrderedDict([('type', 'Class_participant__c'),
                                          ('url',
                                           '/services/data/v42.0/sobjects/Class_participant__c/a0C3h0000019rhTEAQ')])),
                            ('Name', 'a0C3h0000019rhT')]),
               OrderedDict([('attributes',
                             OrderedDict([('type', 'Class_participant__c'),
                                          ('url',
                                           '/services/data/v42.0/sobjects/Class_participant__c/a0C3h0000019rkmEAA')])),
                            ('Name', 'a0C3h0000019rkm')]),
               OrderedDict([('attributes',
                             OrderedDict([('type', 'Class_participant__c'),
                                          ('url',
                                           '/services/data/v42.0/sobjects/Class_participant__c/a0C3h0000019seLEAQ')])),
                            ('Name', 'a0C3h0000019seL')]),
               OrderedDict([('attributes',
                             OrderedDict([('type', 'Class_participant__c'),
                                          ('url',
                                           '/services/data/v42.0/sobjects/Class_participant__c/a0C3h0000019rjtEAA')])),
                            ('Name', 'a0C3h0000019rjt')]),
               OrderedDict([('attributes',
                             OrderedDict([('type', 'Class_participant__c'),
                                          ('url',
                                           '/services/data/v42.0/sobjects/Class_participant__c/a0C3h0000019scFEAQ')])),
                            ('Name', 'a0C3h0000019scF')]),
               OrderedDict([('attributes',
                             OrderedDict([('type', 'Class_participant__c'),
                                          ('url',
                                           '/services/data/v42.0/sobjects/Class_participant__c/a0C3h0000019sdXEAQ')])),
                            ('Name', 'a0C3h0000019sdX')]),
               OrderedDict([('attributes',
                             OrderedDict([('type', 'Class_participant__c'),
                                          ('url',
                                           '/services/data/v42.0/sobjects/Class_participant__c/a0C3h0000019rivEAA')])),
                            ('Name', 'a0C3h0000019riv')]),
               OrderedDict([('attributes',
                             OrderedDict([('type', 'Class_participant__c'),
                                          ('url',
                                           '/services/data/v42.0/sobjects/Class_participant__c/a0C3h0000019scUEAQ')])),
                            ('Name', 'a0C3h0000019scU')]),
               OrderedDict([('attributes',
                             OrderedDict([('type', 'Class_participant__c'),
                                          ('url',
                                           '/services/data/v42.0/sobjects/Class_participant__c/a0C3h0000019seaEAA')])),
                            ('Name', 'a0C3h0000019sea')]),
               OrderedDict([('attributes',
                             OrderedDict([('type', 'Class_participant__c'),
                                          ('url',
                                           '/services/data/v42.0/sobjects/Class_participant__c/a0C3h0000019sasEAA')])),
                            ('Name', 'a0C3h0000019sas')]),
               OrderedDict([('attributes',
                             OrderedDict([('type', 'Class_participant__c'),
                                          ('url',
                                           '/services/data/v42.0/sobjects/Class_participant__c/a0C3h0000019scyEAA')])),
                            ('Name', 'a0C3h0000019scy')]),
               OrderedDict([('attributes',
                             OrderedDict([('type', 'Class_participant__c'),
                                          ('url',
                                           '/services/data/v42.0/sobjects/Class_participant__c/a0C3h0000019ri7EAA')])),
                            ('Name', 'a0C3h0000019ri7')]),
               OrderedDict([('attributes',
                             OrderedDict([('type', 'Class_participant__c'),
                                          ('url',
                                           '/services/data/v42.0/sobjects/Class_participant__c/a0C3h0000019sa4EAA')])),
                            ('Name', 'a0C3h0000019sa4')]),
               OrderedDict([('attributes',
                             OrderedDict([('type', 'Class_participant__c'),
                                          ('url',
                                           '/services/data/v42.0/sobjects/Class_participant__c/a0C3h0000019scZEAQ')])),
                            ('Name', 'a0C3h0000019scZ')]),
               OrderedDict([('attributes',
                             OrderedDict([('type', 'Class_participant__c'),
                                          ('url',
                                           '/services/data/v42.0/sobjects/Class_participant__c/a0C3h0000019sfYEAQ')])),
                            ('Name', 'a0C3h0000019sfY')]),
               OrderedDict([('attributes',
                             OrderedDict([('type', 'Class_participant__c'),
                                          ('url',
                                           '/services/data/v42.0/sobjects/Class_participant__c/a0C3h0000019sgHEAQ')])),
                            ('Name', 'a0C3h0000019sgH')]),
               OrderedDict([('attributes',
                             OrderedDict([('type', 'Class_participant__c'),
                                          ('url',
                                           '/services/data/v42.0/sobjects/Class_participant__c/a0C3h0000019sh0EAA')])),
                            ('Name', 'a0C3h0000019sh0')]),
               OrderedDict([('attributes',
                             OrderedDict([('type', 'Class_participant__c'),
                                          ('url',
                                           '/services/data/v42.0/sobjects/Class_participant__c/a0C3h0000019rkXEAQ')])),
                            ('Name', 'a0C3h0000019rkX')]),
               OrderedDict([('attributes',
                             OrderedDict([('type', 'Class_participant__c'),
                                          ('url',
                                           '/services/data/v42.0/sobjects/Class_participant__c/a0C3h0000019sheEAA')])),
                            ('Name', 'a0C3h0000019she')]),
               OrderedDict([('attributes',
                             OrderedDict([('type', 'Class_participant__c'),
                                          ('url',
                                           '/services/data/v42.0/sobjects/Class_participant__c/a0C3h0000019seVEAQ')])),
                            ('Name', 'a0C3h0000019seV')]),
               OrderedDict([('attributes',
                             OrderedDict([('type', 'Class_participant__c'),
                                          ('url',
                                           '/services/data/v42.0/sobjects/Class_participant__c/a0C3h0000019saJEAQ')])),
                            ('Name', 'a0C3h0000019saJ')]),
               OrderedDict([('attributes',
                             OrderedDict([('type', 'Class_participant__c'),
                                          ('url',
                                           '/services/data/v42.0/sobjects/Class_participant__c/a0C3h0000019rj0EAA')])),
                            ('Name', 'a0C3h0000019rj0')]),
               OrderedDict([('attributes',
                             OrderedDict([('type', 'Class_participant__c'),
                                          ('url',
                                           '/services/data/v42.0/sobjects/Class_participant__c/a0C3h0000019shoEAA')])),
                            ('Name', 'a0C3h0000019sho')]),
               OrderedDict([('attributes',
                             OrderedDict([('type', 'Class_participant__c'),
                                          ('url',
                                           '/services/data/v42.0/sobjects/Class_participant__c/a0C3h0000019scAEAQ')])),
                            ('Name', 'a0C3h0000019scA')]),
               OrderedDict([('attributes',
                             OrderedDict([('type', 'Class_participant__c'),
                                          ('url',
                                           '/services/data/v42.0/sobjects/Class_participant__c/a0C3h0000019rhYEAQ')])),
                            ('Name', 'a0C3h0000019rhY')]),
               OrderedDict([('attributes',
                             OrderedDict([('type', 'Class_participant__c'),
                                          ('url',
                                           '/services/data/v42.0/sobjects/Class_participant__c/a0C3h0000019sbMEAQ')])),
                            ('Name', 'a0C3h0000019sbM')]),
               OrderedDict([('attributes',
                             OrderedDict([('type', 'Class_participant__c'),
                                          ('url',
                                           '/services/data/v42.0/sobjects/Class_participant__c/a0C3h0000019riqEAA')])),
                            ('Name', 'a0C3h0000019riq')]),
               OrderedDict([('attributes',
                             OrderedDict([('type', 'Class_participant__c'),
                                          ('url',
                                           '/services/data/v42.0/sobjects/Class_participant__c/a0C3h0000019sbgEAA')])),
                            ('Name', 'a0C3h0000019sbg')]),
               OrderedDict([('attributes',
                             OrderedDict([('type', 'Class_participant__c'),
                                          ('url',
                                           '/services/data/v42.0/sobjects/Class_participant__c/a0C3h0000019scPEAQ')])),
                            ('Name', 'a0C3h0000019scP')]),
               OrderedDict([('attributes',
                             OrderedDict([('type', 'Class_participant__c'),
                                          ('url',
                                           '/services/data/v42.0/sobjects/Class_participant__c/a0C3h0000019sZzEAI')])),
                            ('Name', 'a0C3h0000019sZz')]),
               OrderedDict([('attributes',
                             OrderedDict([('type', 'Class_participant__c'),
                                          ('url',
                                           '/services/data/v42.0/sobjects/Class_participant__c/a0C3h0000019sbWEAQ')])),
                            ('Name', 'a0C3h0000019sbW')]),
               OrderedDict([('attributes',
                             OrderedDict([('type', 'Class_participant__c'),
                                          ('url',
                                           '/services/data/v42.0/sobjects/Class_participant__c/a0C3h0000019sZuEAI')])),
                            ('Name', 'a0C3h0000019sZu')]),
               OrderedDict([('attributes',
                             OrderedDict([('type', 'Class_participant__c'),
                                          ('url',
                                           '/services/data/v42.0/sobjects/Class_participant__c/a0C3h0000019sa9EAA')])),
                            ('Name', 'a0C3h0000019sa9')]),
               OrderedDict([('attributes',
                             OrderedDict([('type', 'Class_participant__c'),
                                          ('url',
                                           '/services/data/v42.0/sobjects/Class_participant__c/a0C3h0000019rjyEAA')])),
                            ('Name', 'a0C3h0000019rjy')]),
               OrderedDict([('attributes',
                             OrderedDict([('type', 'Class_participant__c'),
                                          ('url',
                                           '/services/data/v42.0/sobjects/Class_participant__c/a0C3h0000019rhiEAA')])),
                            ('Name', 'a0C3h0000019rhi')]),
               OrderedDict([('attributes',
                             OrderedDict([('type', 'Class_participant__c'),
                                          ('url',
                                           '/services/data/v42.0/sobjects/Class_participant__c/a0C3h0000019rigEAA')])),
                            ('Name', 'a0C3h0000019rig')]),
               OrderedDict([('attributes',
                             OrderedDict([('type', 'Class_participant__c'),
                                          ('url',
                                           '/services/data/v42.0/sobjects/Class_participant__c/a0C3h0000019rjjEAA')])),
                            ('Name', 'a0C3h0000019rjj')]),
               OrderedDict([('attributes',
                             OrderedDict([('type', 'Class_participant__c'),
                                          ('url',
                                           '/services/data/v42.0/sobjects/Class_participant__c/a0C3h0000019sh5EAA')])),
                            ('Name', 'a0C3h0000019sh5')]),
               OrderedDict([('attributes',
                             OrderedDict([('type', 'Class_participant__c'),
                                          ('url',
                                           '/services/data/v42.0/sobjects/Class_participant__c/a0C3h0000019shAEAQ')])),
                            ('Name', 'a0C3h0000019shA')]),
               OrderedDict([('attributes',
                             OrderedDict([('type', 'Class_participant__c'),
                                          ('url',
                                           '/services/data/v42.0/sobjects/Class_participant__c/a0C3h0000019rkwEAA')])),
                            ('Name', 'a0C3h0000019rkw')]),
               OrderedDict([('attributes',
                             OrderedDict([('type', 'Class_participant__c'),
                                          ('url',
                                           '/services/data/v42.0/sobjects/Class_participant__c/a0C3h0000019saxEAA')])),
                            ('Name', 'a0C3h0000019sax')]),
               OrderedDict([('attributes',
                             OrderedDict([('type', 'Class_participant__c'),
                                          ('url',
                                           '/services/data/v42.0/sobjects/Class_participant__c/a0C3h0000019saYEAQ')])),
                            ('Name', 'a0C3h0000019saY')]),
               OrderedDict([('attributes',
                             OrderedDict([('type', 'Class_participant__c'),
                                          ('url',
                                           '/services/data/v42.0/sobjects/Class_participant__c/a0C3h0000019sg2EAA')])),
                            ('Name', 'a0C3h0000019sg2')]),
               OrderedDict([('attributes',
                             OrderedDict([('type', 'Class_participant__c'),
                                          ('url',
                                           '/services/data/v42.0/sobjects/Class_participant__c/a0C3h0000019scjEAA')])),
                            ('Name', 'a0C3h0000019scj')]),
               OrderedDict([('attributes',
                             OrderedDict([('type', 'Class_participant__c'),
                                          ('url',
                                           '/services/data/v42.0/sobjects/Class_participant__c/a0C3h0000019sgvEAA')])),
                            ('Name', 'a0C3h0000019sgv')]),
               OrderedDict([('attributes',
                             OrderedDict([('type', 'Class_participant__c'),
                                          ('url',
                                           '/services/data/v42.0/sobjects/Class_participant__c/a0C3h0000019sdrEAA')])),
                            ('Name', 'a0C3h0000019sdr')]),
               OrderedDict([('attributes',

In [53]:
#recs_to_delete = [{'Name': r['Name']} for r in course_records['records']]
#recs_to_delete

[{'Name': 'a0C3h0000019riR'},
 {'Name': 'a0C3h0000019ril'},
 {'Name': 'a0C3h0000019rjK'},
 {'Name': 'a0C3h0000019rkS'},
 {'Name': 'a0C3h0000019riW'},
 {'Name': 'a0C3h0000019rgk'},
 {'Name': 'a0C3h0000019rjP'},
 {'Name': 'a0C3h0000019sZa'},
 {'Name': 'a0C3h0000019sZb'},
 {'Name': 'a0C3h0000019rhs'},
 {'Name': 'a0C3h0000019rgz'},
 {'Name': 'a0C3h0000019rhT'},
 {'Name': 'a0C3h0000019rkm'},
 {'Name': 'a0C3h0000019seL'},
 {'Name': 'a0C3h0000019rjt'},
 {'Name': 'a0C3h0000019scF'},
 {'Name': 'a0C3h0000019sdX'},
 {'Name': 'a0C3h0000019riv'},
 {'Name': 'a0C3h0000019scU'},
 {'Name': 'a0C3h0000019sea'},
 {'Name': 'a0C3h0000019sas'},
 {'Name': 'a0C3h0000019scy'},
 {'Name': 'a0C3h0000019ri7'},
 {'Name': 'a0C3h0000019sa4'},
 {'Name': 'a0C3h0000019scZ'},
 {'Name': 'a0C3h0000019sfY'},
 {'Name': 'a0C3h0000019sgH'},
 {'Name': 'a0C3h0000019sh0'},
 {'Name': 'a0C3h0000019rkX'},
 {'Name': 'a0C3h0000019she'},
 {'Name': 'a0C3h0000019seV'},
 {'Name': 'a0C3h0000019saJ'},
 {'Name': 'a0C3h0000019rj0'},
 {'Name': 'a0C3h0000019sho'},
 {'Name': 'a0C3h0000019scA'},
 {'Name': 'a0C3h0000019rhY'},
 {'Name': 'a0C3h0000019sbM'},
 {'Name': 'a0C3h0000019riq'},
 {'Name': 'a0C3h0000019sbg'},
 {'Name': 'a0C3h0000019scP'},
 {'Name': 'a0C3h0000019sZz'},
 {'Name': 'a0C3h0000019sbW'},
 {'Name': 'a0C3h0000019sZu'},
 {'Name': 'a0C3h0000019sa9'},
 {'Name': 'a0C3h0000019rjy'},
 {'Name': 'a0C3h0000019rhi'},
 {'Name': 'a0C3h0000019rig'},
 {'Name': 'a0C3h0000019rjj'},
 {'Name': 'a0C3h0000019sh5'},
 {'Name': 'a0C3h0000019shA'},
 {'Name': 'a0C3h0000019rkw'},
 {'Name': 'a0C3h0000019sax'},
 {'Name': 'a0C3h0000019saY'},
 {'Name': 'a0C3h0000019sg2'},
 {'Name': 'a0C3h0000019scj'},
 {'Name': 'a0C3h0000019sgv'},
 {'Name': 'a0C3h0000019sdr'},
 {'Name': 'a0C3h0000019sfJ'},
 {'Name': 'a0C3h0000019shF'},
 {'Name': 'a0C3h0000019sgR'},
 {'Name': 'a0C3h0000019sf9'},
 {'Name': 'a0C3h0000019seG'},
 {'Name': 'a0C3h0000019sbv'},
 {'Name': 'a0C3h0000019si8'},
 {'Name': 'a0C3h0000019sce'},
 {'Name': 'a0C3h0000019scf'},
 {'Name': 'a0C3h0000019shU'},
 {'Name': 'a0C3h0000019sdD'},
 {'Name': 'a0C3h0000019sdE'},
 {'Name': 'a0C3h0000019sgb'},
 {'Name': 'a0C3h0000019sd8'},
 {'Name': 'a0C3h0000019siI'},
 {'Name': 'a0C3h0000019shj'},
 {'Name': 'a0C3h0000019se1'},
 {'Name': 'a0C3h0000019sgM'},
 {'Name': 'a0C3h0000019shZ'},
 {'Name': 'a0C3h0000019sai'},
 {'Name': 'a0C3h0000019rjZ'},
 {'Name': 'a0C3h0000019sf4'},
 {'Name': 'a0C3h0000019sfn'},
 {'Name': 'a0C3h0000019rkD'},
 {'Name': 'a0C3h0000019riC'},
 {'Name': 'a0C3h0000019riM'},
 {'Name': 'a0C3h0000019rjo'},
 {'Name': 'a0C3h0000019sdh'},
 {'Name': 'a0C3h0000019sez'},
 {'Name': 'a0C3h0000019sfi'},
 {'Name': 'a0C3h0000019sdN'},
 {'Name': 'a0C3h0000019rk3'},
 {'Name': 'a0C3h0000019sco'},
 {'Name': 'a0C3h0000019sef'},
 {'Name': 'a0C3h0000019sfT'},
 {'Name': 'a0C3h0000019rkr'},
 {'Name': 'a0C3h0000019sad'},
 {'Name': 'a0C3h0000019rgp'},
 {'Name': 'a0C3h0000019rj5'},
 {'Name': 'a0C3h0000019rkh'},
 {'Name': 'a0C3h0000019sc5'},
 {'Name': 'a0C3h0000019sgg'},
 {'Name': 'a0C3h0000019sfx'},
 {'Name': 'a0C3h0000019rhJ'},
 {'Name': 'a0C3h0000019rhK'},
 {'Name': 'a0C3h0000019rjA'},
 {'Name': 'a0C3h0000019sbq'},
 {'Name': 'a0C3h0000019rh9'},
 {'Name': 'a0C3h0000019rhA'},
 {'Name': 'a0C3h0000019rgf'},
 {'Name': 'a0C3h0000019rgu'},
 {'Name': 'a0C3h0000019sZk'},
 {'Name': 'a0C3h0000019sbC'},
 {'Name': 'a0C3h0000019sc0'},
 {'Name': 'a0C3h0000019seQ'},
 {'Name': 'a0C3h0000019sbl'},
 {'Name': 'a0C3h0000019sfd'},
 {'Name': 'a0C3h0000019sg7'},
 {'Name': 'a0C3h0000019sgl'},
 {'Name': 'a0C3h0000019shP'},
 {'Name': 'a0C3h0000019sbb'},
 {'Name': 'a0C3h0000019sdS'},
 {'Name': 'a0C3h0000019saE'},
 {'Name': 'a0C3h0000019shy'},
 {'Name': 'a0C3h0000019sfs'},
 {'Name': 'a0C3h0000019sb7'},
 {'Name': 'a0C3h0000019san'},
 {'Name': 'a0C3h0000019rjU'},
 {'Name': 'a0C3h0000019sdm'},
 {'Name': 'a0C3h0000019se6'},
 {'Name': 'a0C3h0000019rhO'},
 {'Name': 'a0C3h0000019rhx'},
 {'Name': 'a0C3h0000019sfE'},
 {'Name': 'a0C3h0000019sd3'},
 {'Name': 'a0C3h0000019sZp'},
 {'Name': 'a0C3h0000019siD'},
 {'Name': 'a0C3h0000019rjF'},
 {'Name': 'a0C3h0000019rib'},
 {'Name': 'a0C3h0000019sdI'},
 {'Name': 'a0C3h0000019saO'},
 {'Name': 'a0C3h0000019rh4'},
 {'Name': 'a0C3h0000019riH'},
 {'Name': 'a0C3h0000019rk8'},
 {'Name': 'a0C3h0000019ri2'},
 {'Name': 'a0C3h0000019rkN'},
 {'Name': 'a0C3h0000019rkI'},
 {'Name': 'a0C3h0000019rje'},
 {'Name': 'a0C3h0000019sgq'},
 {'Name': 'a0C3h0000019scK'},
 {'Name': 'a0C3h0000019sdc'},
 {'Name': 'a0C3h0000019sct'},
 {'Name': 'a0C3h0000019sdw'},
 {'Name': 'a0C3h0000019saT'},
 {'Name': 'a0C3h0000019sbR'},
 {'Name': 'a0C3h0000019sek'},
 {'Name': 'a0C3h0000019sgC'},
 {'Name': 'a0C3h0000019sgW'},
 {'Name': 'a0C3h0000019sbH'},
 {'Name': 'a0C3h0000019rhn'},
 {'Name': 'a0C3h0000019si3'},
 {'Name': 'a0C3h0000019shK'},
 {'Name': 'a0C3h0000019rhd'},
 {'Name': 'a0C3h0000019seB'},
 {'Name': 'a0C3h0000019sht'},
 {'Name': 'a0C3h0000019sZf'},
 {'Name': 'a0C3h0000019sb2'},
 {'Name': 'a0C3h0000019sfO'},
 {'Name': 'a0C3h0000019rhE'},
 {'Name': 'a0C3h0000019sep'},
 {'Name': 'a0C3h0000019rkc'},
 {'Name': 'a0C3h0000019seu'}]

In [54]:
# Loop through the record ID list and delete individual records
#for rec in recs_to_delete:
#    try:
#        sf.Class_participant__c.delete(rec['Name'])
#    except Exception as e:
#        print(e)